# Generated by Django 5.2.10 on 2026-02-02 04:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название опции')),
                ('category', models.CharField(choices=[('comfort', 'Комфорт'), ('safety', 'Безопасность'), ('multimedia', 'Мультимедиа'), ('exterior', 'Экстерьер'), ('other', 'Другое')], max_length=50, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Опция автомобиля',
                'verbose_name_plural': 'Опции автомобилей',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2024)], verbose_name='Год выпуска')),
                ('engine_volume', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Объем двигателя (л)')),
                ('engine_type', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('hybrid', 'Гибрид'), ('electric', 'Электро'), ('gas', 'Газ/Бензин')], max_length=20, verbose_name='Тип двигателя')),
                ('transmission', models.CharField(choices=[('manual', 'Механическая'), ('automatic', 'Автоматическая'), ('robot', 'Роботизированная'), ('variator', 'Вариатор')], max_length=20, verbose_name='Коробка передач')),
                ('drive_type', models.CharField(choices=[('front', 'Передний'), ('rear', 'Задний'), ('all', 'Полный')], max_length=20, verbose_name='Привод')),
                ('horsepower', models.IntegerField(verbose_name='Мощность (л.с.)')),
                ('mileage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Пробег (км)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (руб)')),
                ('owners_count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество владельцев')),
                ('accidents', models.TextField(blank=True, help_text='Описание аварий, если были', null=True, verbose_name='История ДТП')),
                ('has_accidents', models.BooleanField(default=False, verbose_name='Участвовал в ДТП')),
                ('was_taxi', models.BooleanField(default=False, verbose_name='Использовался в такси')),
                ('taxi_years', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Лет в такси')),
                ('repair_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая стоимость ремонтов (руб)')),
                ('yearly_maintenance', models.DecimalField(decimal_places=2, help_text='Приблизительная стоимость обслуживания машины в год', max_digits=10, verbose_name='Среднее обслуживание в год (руб)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Продано')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['brand', 'model'], name='cars_car_brand_812f04_idx'), models.Index(fields=['year'], name='cars_car_year_fc6735_idx'), models.Index(fields=['price'], name='cars_car_price_f6b08b_idx'), models.Index(fields=['mileage'], name='cars_car_mileage_f4d08e_idx')],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/images/', verbose_name='Фотография')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Фотография автомобиля',
                'verbose_name_plural': 'Фотографии автомобилей',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата обслуживания')),
                ('service_type', models.CharField(max_length=100, verbose_name='Вид обслуживания')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость (руб)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание работ')),
                ('mileage_at_service', models.IntegerField(verbose_name='Пробег при обслуживании')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='cars.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Запись обслуживания',
                'verbose_name_plural': 'История обслуживания',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CarFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_features', to='cars.car', verbose_name='Автомобиль')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carfeature', verbose_name='Опция')),
            ],
            options={
                'verbose_name': 'Опция автомобиля',
                'verbose_name_plural': 'Опции автомобилей',
                'unique_together': {('car', 'feature')},
            },
        ),
    ]
