# Generated by Django 6.0.2 on 2026-02-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Underwear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('gender', models.CharField(choices=[('men', 'Мужские'), ('women', 'Женские'), ('unisex', 'Унисекс')], default='unisex', max_length=10, verbose_name='Пол')),
                ('underwear_type', models.CharField(choices=[('briefs', 'Трусы-плавки'), ('boxers', 'Боксеры'), ('thong', 'Стринги'), ('bikini', 'Бикини'), ('high_cut', 'Хай-кат'), ('other', 'Другое')], default='briefs', max_length=20, verbose_name='Тип')),
                ('material', models.CharField(help_text='Например: хлопок, полиэстер и т.д.', max_length=100, verbose_name='Материал')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('size', models.CharField(max_length=10, verbose_name='Размер')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Трусы',
                'verbose_name_plural': 'Трусы',
            },
        ),
    ]
